* Config
** Set gc threshold more

   #+begin_src emacs-lisp
     (setq gc-cons-threshold (* 50 1000 1000))
   #+end_src

** Config management
   `C-x C-l` reloads the init-file.

   #+BEGIN_SRC emacs-lisp
     (defun reload-init-file ()
       (interactive)
       (load-file "~/.emacs.d/init.el")
       (princ "Init-file reloaded."))

     (global-set-key (kbd "C-x C-l") 'reload-init-file)
   #+END_SRC

** Package management
*** straight.el

    Bootstrap straight.el.

    #+BEGIN_SRC emacs-lisp
      (defvar bootstrap-version)
      (let ((bootstrap-file
             (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
            (bootstrap-version 5))
        (unless (file-exists-p bootstrap-file)
          (with-current-buffer
              (url-retrieve-synchronously
               "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
               'silent 'inhibit-cookies)
            (goto-char (point-max))
            (eval-print-last-sexp)))
        (load bootstrap-file nil 'nomessage))
    #+END_SRC

*** use-package

    Bootstrap use-package and activate `chords' extension.

    #+BEGIN_SRC emacs-lisp
      (straight-use-package 'use-package)
      (setq straight-use-package-by-default t
         use-package-always-demand t)
      (use-package use-package-chords
        :config (key-chord-mode 1))
    #+END_SRC

** Profiling
*** Esup

    Type "M-x esup" to start profiling.

   #+begin_src emacs-lisp
     (use-package esup
       :commands (esup))
   #+end_src

** Essentials
*** Sane defaults

    At startup.

    #+BEGIN_SRC emacs-lisp
      (toggle-scroll-bar -1)
      (add-to-list 'default-frame-alist '(vertical-scroll-bars . nil))
      (add-to-list 'default-frame-alist '(height . 44))
      (add-to-list 'default-frame-alist '(width . 184))
      (menu-bar-mode -1)
      (tool-bar-mode -1)
      (blink-cursor-mode -1)

      (setq-default
       indicate-empty-lines 1
       tab-width 4
       fill-column 80
       indent-tabs-mode nil)

      (fset 'display-startup-echo-area-message 'ignore)

      (setq
       initial-buffer-choice t
       scroll-conservatively most-positive-fixnum
       column-number-mode t
       auto-save-timeout 60
       load-prefer-newer t
       read-file-name-completion-ignore-case t
       indent-tabs-mode nil
       require-final-newline t
       uniquify-buffer-name-style 'forward
       create-lockfiles nil
       backup-directory-alist '(("." . "~/.emacs.d/backup"))
       backup-by-copying t                 ; Don't delink hardlinks
       version-control t                   ; Use version numbers on backups
       delete-old-versions t               ; Automatically delete excess backups
       kept-new-versions 20                ; how many of the newest versions to keep
       kept-old-versions 5                 ; and how many of the old
       dired-dwim-target t
       vc-follow-symlinks t
       recentf-max-menu-items 100
       recentf-max-saved-items 100
       )
     #+END_SRC

     After startup.

     #+begin_src emacs-lisp
       (use-package autorevert
         :defer 2
         :config (global-auto-revert-mode 1))

       (use-package delsel
         :defer 2
         :config (delete-selection-mode 1))

       (use-package subword
         :defer 2
         :config (global-subword-mode 1))

       (use-package recentf
         :defer 1
         :config (recentf-mode 1))

       (add-hook 'prog-mode-hook 'my-prog-mode-hook)
       (defun my-prog-mode-hook ()
         "Prog mode hook consisting of built-in functions and packages."
         (setq show-trailing-whitespace t))
     #+end_src

** Font
*** Fantasque Sans Mono

    Use Fantasque Sans Mono font with ligatures.

    #+begin_src emacs-lisp
      ;; On MacOS due to retina display font should be bigger.
      (if (eq system-type 'darwin)
      (set-face-attribute 'default nil :font "Fantasque Sans Mono" :height 120)
        (set-face-attribute 'default nil :font "Fantasque Sans Mono" :height 90))

      (let ((alist `((?& . ,(regexp-opt '("&&")))
                     (?* . ,(regexp-opt '("*/")))
                     (?| . ,(regexp-opt '("|||>" "||>" "||" "|>")))
                     (?: . ,(regexp-opt '("::")))
                     (?= . ,(regexp-opt '("===" "==>" "==" "=>>" "=>" "=<<" "=/=")))
                     (?! . ,(regexp-opt '("!==" "!=")))
                     (?> . ,(regexp-opt '(">=>" ">=" ">>=" ">>-" ">>" ">->" ">-")))
                     (?- . ,(regexp-opt '("->>" "->" "-->" "-<<" "-<")))
                     (?< . ,(regexp-opt '("<|||" "<||" "<|>" "<|" "<==" "<=>" "<=<" "<=" "<!--" "<>" "<->"
                                          "<--" "<-<" "<-" "<<=" "<<-" "<<" "<~>" "<~" "<~~")))
                     (?/ . ,(regexp-opt '("/**/" "/*" "//")))
                     (?~ . ,(regexp-opt '("~>" "~~>" "~~"))))))
        (dolist (char-regexp alist)
      (set-char-table-range composition-function-table (car char-regexp)
                    `([,(cdr char-regexp) 0 font-shape-gstring]))))
    #+end_src

** Org-mode
*** Shortcuts

    #+BEGIN_SRC emacs-lisp
      (add-hook 'org-mode-hook (lambda () (require 'org-tempo)))
    #+END_SRC

*** Org-bullets

    #+BEGIN_SRC emacs-lisp
      (use-package org-bullets
        :defer t
        :hook (org-mode . org-bullets-mode))
    #+END_SRC

** Theme
*** Cyberpunk
    Cool cyberpunk theme.

    # #+BEGIN_SRC emacs-lisp
    #   (use-package cyberpunk-theme
    #     :config (load-theme 'cyberpunk t)
    # 	:custom-face
    #     (ivy-virtual ((t (:inherit font-lock-constant-face)))))
    # #+END_SRC

*** My cyberpunk

    #+BEGIN_SRC emacs-lisp
      (straight-use-package
       '(cyberpunk-theme :type git :flavor melpa :host github :repo "n3mo/cyberpunk-theme.el"
                      :fork (:repo "greenfork/cyberpunk-theme.el" :host github :branch "add-diredfl-support")))
      (load-theme 'cyberpunk t)
      (global-set-key (kbd "C-h z") 'face-at-point)
    #+END_SRC

** Keybindings
*** Saner defaults

    #+BEGIN_SRC emacs-lisp
      (global-set-key (kbd "C-x C-b") 'ibuffer)
      (global-set-key (kbd "M-/") 'hippie-expand)
      (global-set-key (kbd "C-z") nil)
      (global-set-key (kbd "C-x k") 'kill-current-buffer)
      (global-set-key (kbd "C-x K") 'kill-buffer)
    #+END_SRC

*** Keychords

    Use fast key presses in the same way as sequential combinations.

    #+BEGIN_SRC emacs-lisp
      (use-package key-chord)
    #+END_SRC

** Window management
*** Winner

    Restore previous window configuration e.g. after `C-x 1'.

    #+BEGIN_SRC emacs-lisp
      (use-package winner
        :config (winner-mode 1))
    #+END_SRC

*** Ace-window

    Jump to windows you choose.

    #+BEGIN_SRC emacs-lisp
      (use-package ace-window
        :defer t
        :bind (("C-x o" . ace-window)))
    #+END_SRC

*** Windmove

    Choose direction to move between buffers.

    #+BEGIN_SRC emacs-lisp
      (global-set-key (kbd "C-M-h") 'windmove-left)
      (global-set-key (kbd "C-M-j") 'windmove-down)
      (global-set-key (kbd "C-M-k") 'windmove-up)
      (global-set-key (kbd "C-M-l") 'windmove-right)
    #+END_SRC

** UI
*** Diminish

    Diminish hides modes in modeline. Make sure it is loaded before any other mode
    uses `:diminish' option.

    #+BEGIN_SRC emacs-lisp
      (use-package diminish
        :config (progn
               (diminish 'eldoc-mode)
               (diminish 'subword-mode)))
    #+END_SRC

*** Ibuffer

    Group by projectile projects.

    #+BEGIN_SRC emacs-lisp
      (use-package ibuffer-projectile
        :defer t
        :hook (ibuffer . ibuffer-projectile-set-filter-groups)
        :config
        (setq ibuffer-projectile-prefix "Project: "))
    #+END_SRC

*** Dired

    Add fancy highlighting to dired.

    #+BEGIN_SRC emacs-lisp
      (use-package diredfl
        :defer t
        :hook (dired-mode . diredfl-mode))
    #+END_SRC

    Display git info by pressing right paren in dired.

    #+BEGIN_SRC emacs-lisp
      (use-package dired-git-info
        :defer t
        :bind (:map dired-mode-map
                 (")" . dired-git-info-mode)))
    #+END_SRC

*** fill-column-indicator

    #+begin_src emacs-lisp
      (use-package display-fill-column-indicator
        :hook (prog-mode . display-fill-column-indicator-mode))
    #+end_src

*** Rainbow delimiters

    Colored parens depending of their nest level.

    #+BEGIN_SRC emacs-lisp
      (use-package rainbow-delimiters
        :defer t
        :hook (prog-mode . rainbow-delimiters-mode))
    #+END_SRC

*** Ido-yes-or-no

    Quickly answer annoying questions with a single letter.

    #+BEGIN_SRC emacs-lisp
      (use-package ido-yes-or-no
        :config (ido-yes-or-no-mode 1))
    #+END_SRC

*** Which-key

    Show possible key shortcuts after pressing e.g. `C-x'.

    #+BEGIN_SRC emacs-lisp
      (use-package which-key
        :diminish
        :config (which-key-mode t))
    #+END_SRC

** Source control
*** Magit

    Porcelain wrapper around git.

    #+BEGIN_SRC emacs-lisp
      (use-package magit
        :defer t)
    #+END_SRC

*** diff-hl

    Show git status in fringes.

    #+BEGIN_SRC emacs-lisp
      (use-package diff-hl
        :defer 2
        :config (global-diff-hl-mode)
        :hook ((magit-pre-refresh-hook . diff-hl-magit-pre-refresh)
               (magit-post-refresh-hook . diff-hl-magit-post-refresh)))

      ;; Workaround to not clip fringes https://github.com/dgutov/diff-hl/issues/94
      (setq window-divider-default-places 'right-only) ;Default 'right-only
      (setq window-divider-default-right-width 1) ;Default 6
      (window-divider-mode 1)
    #+END_SRC

** Completion
*** Company

    Completion of text as you type.
    Complete selected item with `C-f', `Enter' should produce newline.

    #+BEGIN_SRC emacs-lisp
      (use-package company
        :diminish
        :defer 1
        :init
        (setq company-idle-delay 0.4
           company-minimum-prefix-length 2
           company-tooltip-limit 16
           company-tooltip-align-annotations t
           company-require-match 'never)
        :config (progn
               (global-company-mode)
               (define-key company-active-map (kbd "M-n") nil)
               (define-key company-active-map (kbd "M-p") nil)
               (define-key company-active-map (kbd "RET") nil)
               (define-key company-active-map [return] nil)
               (define-key company-active-map (kbd "C-n") 'company-select-next)
               (define-key company-active-map (kbd "C-p") 'company-select-previous)
               (define-key company-active-map (kbd "C-f") 'company-complete-selection)))
    #+END_SRC

*** Ivy

    General completion framework for all sorts of commands.

    #+BEGIN_SRC emacs-lisp
      (use-package counsel
        :diminish
        :defer 0.3
        :config
        (ivy-mode 1)
        (counsel-mode 1)
        (setq ivy-use-virtual-buffers t
           ivy-count-format "(%d/%d) "
           ivy-height 17
           ivy-on-del-error-function #'ignore))

      (diminish 'ivy-mode)

      ;; Standard keybindings
      (global-set-key (kbd "C-s") 'swiper-isearch)
      (global-set-key (kbd "C-x b") 'ivy-switch-buffer)
      (global-set-key (kbd "C-.") 'counsel-semantic-or-imenu)

      ;; Resume commands
      (global-set-key (kbd "C-c C-r") 'ivy-resume)

      (use-package ivy-rich
        :after ivy
        :config
        (ivy-rich-mode 1)
        (setq ivy-rich-parse-remote-buffer nil
           ivy-rich-path-style 'abbrev))
    #+END_SRC

*** Amx

    Better completion of `M-x'. Also adds `M-X' for major mode specific commands.

    #+BEGIN_SRC emacs-lisp
      (use-package amx
        :defer 2
        :config (amx-mode)
        :bind (("M-X" . amx-major-mode-commands)))
    #+END_SRC

** Source discovery
*** Helpful

    Show more info in help views.

    #+BEGIN_SRC emacs-lisp
      (use-package helpful
        :defer t
        :bind (("C-h f" . helpful-callable)
               ("C-h v" . helpful-variable)
               ("C-h k" . helpful-key)
               ("C-c C-d" . helpful-at-point)))
    #+END_SRC

** Source navigation
*** Avy

    Quickly type `jj' and several consequtive characters of the place you want to jump to.

    #+BEGIN_SRC emacs-lisp
      (use-package avy
        :defer t
        :chords (("jj" . avy-goto-char-timer)))
    #+END_SRC

** Project management
*** Projectile

    Magical `C-c p' to access all commands related to a current directory project.

    #+BEGIN_SRC emacs-lisp
      (use-package projectile
        :defer t
        :bind (("C-c p" . projectile-command-map))
        :config
        (projectile-mode +1)
        (setq projectile-completion-system 'ivy))

      (use-package counsel-projectile
        :after projectile
        :config (counsel-projectile-mode))
    #+END_SRC

** Checkers
*** Flycheck

    Check syntax on-the-fly. Almost: checking syntax on the fly gives false
    positives because the line is incomplete and it freezes the system when
    linter is slow.

    #+BEGIN_SRC emacs-lisp
      (use-package flycheck
        :defer 2
        :config
        (global-flycheck-mode)
        (setq flycheck-check-syntax-automatically '(save mode-enabled idle-buffer-switch)
           flycheck-buffer-switch-check-intermediate-buffers t
           flycheck-display-errors-delay 0.25))
    #+END_SRC

** Editing
*** Crux

    Different utility commands.

    #+BEGIN_SRC emacs-lisp
      (use-package crux
        :defer t
        :bind (("M-o" . crux-smart-open-line)
            ("M-O" . crux-smart-open-line-above)
            ("C-c D" . crux-delete-file-and-buffer)
            ("C-c R" . crux-rename-file-and-buffer)
            ("C-^" . crux-top-join-line)
            ([remap move-beginning-of-line] . crux-move-beginning-of-line)
            ("C-c f" . crux-recentf-find-file))
        :config (progn
               (crux-with-region-or-line kill-region)
               (crux-with-region-or-line kill-ring-save))
        :chords ("JJ" . crux-switch-to-previous-buffer))
    #+END_SRC

*** Undo

    Type `uu' to look at and navigate undo tree.

    #+BEGIN_SRC emacs-lisp
      (use-package undo-tree
        :chords ("uu" . undo-tree-visualize)
        :config
        (setq undo-tree-visualizer-diff t
           undo-tree-auto-save-history t
           undo-tree-enable-undo-in-region t
           ;; Increase undo-limits by a factor of ten to avoid emacs prematurely
           ;; truncating the undo history and corrupting the tree. See
           ;; https://github.com/syl20bnr/spacemacs/issues/12110
           undo-limit 800000
           undo-strong-limit 12000000
           undo-outer-limit 120000000)

        ;; Strip text properties from undo-tree data to stave off bloat. File size
        ;; isn't the concern here; undo cache files bloat easily, which can cause
        ;; freezing, crashes, GC-induced stuttering or delays when opening files.
        (defadvice undo-list-transfer-to-tree (before strip-undo-tree-text-properties)
          (dolist (item buffer-undo-list)
         (and (consp item)
              (stringp (car item))
              (setcar item (substring-no-properties (car item)))))))
    #+END_SRC

*** Expand-region

    Consequtively expand the current region by pressing `C-='.
    Shrink it by preceding this command with `C--' (minus).

    #+BEGIN_SRC emacs-lisp
      (use-package expand-region
        :defer t
        :bind ("C-=" . er/expand-region))
    #+END_SRC

*** Wgrep

    Type `C-p' in a grep buffer to make it editable.

    #+BEGIN_SRC emacs-lisp
      (use-package wgrep
        :defer t
        :config (setq wgrep-auto-save-buffer t))
    #+END_SRC

*** Smartparens

    Probably smarter than electric-mode.

    #+BEGIN_SRC emacs-lisp
      (use-package smartparens-config
        :straight smartparens
        :hook
        ((clojure-mode emacs-lisp-mode) . turn-on-smartparens-strict-mode)
        :config
        (show-smartparens-global-mode t)
        (smartparens-global-mode)
        :bind (("M-]" . sp-unwrap-sexp)
               ("M-[" . sp-backward-unwrap-sexp)
               ("C-<right>" . sp-forward-slurp-sexp)
               ("M-<right>" . sp-forward-barf-sexp)
               ("C-<left>" . sp-backward-slurp-sexp)
               ("C-<left>" . sp-backward-barf-sexp)
               ("C-M-a" . sp-beginning-of-sexp)
               ("C-M-e" . sp-end-of-sexp)))
    #+END_SRC

** Languages
*** Ruby

    - ruby-mode
    - slim-mode
    - rubocop
    - minitest
    - projectile-rails

    Nothing too fancy, just standard Ruby stuff.

    #+BEGIN_SRC emacs-lisp
      (use-package ruby-mode
        :defer t
        :config
        (setq ruby-insert-encoding-magic-comment nil))
    #+END_SRC

    Mode for templating enginge "slim".

    #+BEGIN_SRC emacs-lisp
      (use-package slim-mode
        :defer t)
    #+END_SRC

    Mode for linter, mostly for autocorrect feature, because everything
    else is done via Flycheck. Accessible with `M-x'.

    #+BEGIN_SRC emacs-lisp
      (use-package rubocop
        :defer t
        :diminish
        :hook (ruby-mode . rubocop-mode))
    #+END_SRC

    Interface for "minitest" testing framework, accessible via `C-c ,'.

    #+BEGIN_SRC emacs-lisp
      (use-package minitest
        :after projectile-rails
        :diminish
        :hook
        (ruby-mode . (lambda ()
                    ;; Enable rails support.
                    ;; Function body is copied from `projectile-rails-on'.
                    (when (and
                           (not (projectile-rails--ignore-buffer-p))
                           (projectile-project-p)
                           (projectile-rails-root))
                      (setq minitest-use-spring t))

                    (minitest-mode))))
    #+END_SRC

    Access rails-specific commands with `C-c r'.

    #+BEGIN_SRC emacs-lisp
      (use-package projectile-rails
        :diminish
        :after ruby-mode
        :config (projectile-rails-global-mode)
        :bind (:map projectile-rails-mode-map
                 ("C-c r" . projectile-rails-command-map)))
    #+END_SRC

*** JavaScript

    Options are mostly copied from Doom Emacs.
    Install =eslint= for full experience.

    #+BEGIN_SRC emacs-lisp
      (use-package js2-mode
        :defer t
        :mode "\\.m?js\\'"
        :hook (js2-mode . js2-imenu-extras-mode)
        :config
        (setq js-chain-indent t
              ;; Flycheck does it instead.
              js2-mode-show-parse-errors nil
              js2-mode-show-strict-warnings nil
              ;; Conflicting features with eslint.
              js2-strict-trailing-comma-warning nil
              js2-strict-missing-semi-warning nil
              ;; Maximum fontification.
              js2-highlight-level 3
              js2-highlight-external-variables t
              js2-idle-timer-delay 0.2
              js2-basic-offset 2))
    #+END_SRC

    #+BEGIN_SRC emacs-lisp
      (use-package eslint-fix
        :defer t
        :hook (js2-mode . (lambda () (add-hook 'after-save-hook 'eslint-fix nil t))))
    #+END_SRC

*** Yaml

    Just yaml, no fancy stuff here.

    #+BEGIN_SRC emacs-lisp
      (use-package yaml-mode
        :defer t
        :hook (yaml-mode . (lambda () (setq tab-width yaml-indent-offset))))
    #+END_SRC

** REPLs
*** eshell

    Better defaults.

    #+BEGIN_SRC emacs-lisp
      (setq eshell-scroll-to-bottom-on-input 'all
            eshell-scroll-to-bottom-on-output 'all
            eshell-kill-processes-on-exit t
            eshell-hist-ignoredups t)
    #+END_SRC

    Eldoc support.

    #+BEGIN_SRC emacs-lisp
      (use-package esh-help
        :defer t
        :commands eshell
        :config (setup-esh-help-eldoc))
    #+END_SRC

    Eshell-up.

    #+BEGIN_SRC emacs-lisp
      (use-package eshell-up
        :defer t
        :commands (eshell-up eshell-up-peek))
    #+END_SRC

    Eshell-z.

    #+BEGIN_SRC emacs-lisp
      (straight-use-package 'eshell-z)
      (add-hook 'eshell-mode-hook (lambda () (require 'eshell-z)))
    #+END_SRC

** Set gc threshold less

   #+begin_src emacs-lisp
     (setq gc-cons-threshold (* 2 1000 1000))
   #+end_src

